import type { Config, SavedFilter } from "./config"
import { sortTasks, taskDetails } from "./tasks"
import type { Task } from "./todoist"

export const BEGIN_MARKER = "omadoist:begin"
export const END_MARKER = "omadoist:end"

const BEGIN_LINE = `  // >>> ${BEGIN_MARKER} — generated by \`omadoist sync\`; edits inside this block are overwritten`
const END_LINE = `  // <<< ${END_MARKER}`

const ICON_TASK = "\u{F0131}" // 󰄱 checkbox-blank-outline
const ICON_ADD = "\u{F0415}" // 󰐕 plus
const ICON_REFRESH = "\u{F0450}" // 󰑐 refresh
const ICON_WEB = "\u{F059F}" // 󰖟 web
const ICON_LINK = "\u{F0337}" // 󰌷 link-variant
const ICON_FILTER = "\u{F0232}" // 󰈲 filter

const ICON_FILTER_ON = "\u{F0233}" // 󰈳 filter-outline, for the one in force

const MAX_LABEL = 64

export type MenuRow = { id: string; entry: Record<string, unknown> }

/**
 * The submenu row carries the Todoist logo, which lives in its own font; task
 * and command rows stay on the shell's Nerd Font.
 */
function brandIcon(config: Config): Record<string, string> {
  return {
    icon: config.menuIcon,
    ...(config.menuIconFont ? { iconFont: config.menuIconFont } : {}),
  }
}

export function shellQuote(value: string): string {
  return `'${String(value).replace(/'/g, `'\\''`)}'`
}

function truncate(value: string, max = MAX_LABEL): string {
  const text = value.replace(/\s+/g, " ").trim()
  return text.length > max ? text.slice(0, max - 1).trimEnd() + "…" : text
}

/**
 * The rows the menu shows when there is no token yet: one row that opens a
 * terminal on `omadoist auth`, so the menu is never a dead end.
 */
export function buildUnauthenticatedRows(config: Config): MenuRow[] {
  return [
    {
      id: "todoist",
      entry: {
        ...brandIcon(config),
        label: config.menuLabel,
        aliases: ["todo", "tasks", "todoist"],
        description: "Not connected yet",
      },
    },
    {
      id: "todoist.connect",
      entry: {
        icon: ICON_LINK,
        label: "Connect Todoist…",
        description: "Paste an API token from Todoist → Settings → Integrations → Developer",
        action: "omarchy-launch-floating-terminal-with-presentation 'omadoist auth'",
      },
    },
  ]
}

export function buildRows(tasks: Task[], projects: Map<string, string>, config: Config, now = new Date()): MenuRow[] {
  const shown = sortTasks(tasks).slice(0, Math.max(1, config.limit))
  const rows: MenuRow[] = [
    {
      id: "todoist",
      entry: {
        ...brandIcon(config),
        label: config.menuLabel,
        aliases: ["todo", "tasks", "todoist"],
        description: shown.length === 1 ? "1 open task" : `${shown.length} open tasks`,
      },
    },
  ]

  // Row ids are positional so two tasks can never collide on one key; the real
  // Todoist id travels in the action instead.
  shown.forEach((task, index) => {
    const details = config.showDetails ? taskDetails(task, projects, now) : ""
    rows.push({
      id: `todoist.task-${String(index + 1).padStart(3, "0")}`,
      entry: {
        icon: ICON_TASK,
        label: truncate(task.content),
        ...(details ? { description: details } : {}),
        action: `omadoist done ${shellQuote(String(task.id))}`,
      },
    })
  })

  if (shown.length === 0) {
    rows.push({
      id: "todoist.empty",
      entry: {
        icon: ICON_REFRESH,
        label: "No open tasks",
        description: "Check Todoist again",
        action: "omadoist sync --open",
      },
    })
  }

  rows.push(
    {
      id: "todoist.add",
      entry: {
        icon: ICON_ADD,
        label: "New task…",
        action: "omadoist add",
      },
    },
    {
      id: "todoist.filter",
      entry: {
        icon: ICON_FILTER,
        label: "Filter…",
        description: config.filter.trim() || "All active tasks",
        action: "omadoist filter --edit",
      },
    },
    ...savedFilterRows(config),
    {
      id: "todoist.refresh",
      entry: {
        icon: ICON_REFRESH,
        label: "Refresh",
        action: "omadoist sync --open",
      },
    },
    {
      id: "todoist.open",
      entry: {
        icon: ICON_WEB,
        label: "Open Todoist",
        action: "omarchy-launch-webapp 'https://app.todoist.com/app/today'",
      },
    },
  )

  return rows
}

/**
 * One row per saved filter, so the menu can switch between them without the
 * user retyping a query into a prompt. The one in force is marked rather than
 * hidden: seeing which it is, is half of why the row exists.
 */
function savedFilterRows(config: Config): MenuRow[] {
  const current = config.filter.trim()
  return config.filters.map((saved: SavedFilter, index) => {
    const active = saved.query === current
    return {
      id: `todoist.filter-${String(index + 1).padStart(2, "0")}`,
      entry: {
        icon: active ? ICON_FILTER_ON : ICON_FILTER,
        label: truncate(active ? `${saved.name} ✓` : saved.name),
        description: saved.query || "All active tasks",
        action: saved.query ? `omadoist filter ${shellQuote(saved.query)}` : "omadoist filter --clear",
      },
    }
  })
}

export function renderBlock(rows: MenuRow[]): string {
  const lines = rows.map(({ id, entry }) => `  ${JSON.stringify(id)}: ${JSON.stringify(entry)},`)
  return [BEGIN_LINE, ...lines, END_LINE].join("\n")
}

/**
 * Splice the generated block into the user's menu extension, leaving every
 * hand-written row untouched. A previous block is replaced in place; a first
 * run appends just inside the closing brace.
 */
export function mergeIntoMenu(source: string, block: string): string {
  const lines = source.split("\n")
  const begin = lines.findIndex((line) => line.includes(BEGIN_MARKER))
  const end = lines.findIndex((line) => line.includes(END_MARKER))

  if (begin !== -1 && end > begin) {
    return [...lines.slice(0, begin), ...block.split("\n"), ...lines.slice(end + 1)].join("\n")
  }

  const closing = source.lastIndexOf("}")
  if (closing === -1) return `{\n${block}\n}\n`

  const head = source.slice(0, closing).replace(/\s*$/, "")
  const tail = source.slice(closing)
  return `${head}\n\n${block}\n${tail}`
}

/** Drop the generated block again, e.g. on uninstall. */
export function removeFromMenu(source: string): string {
  const lines = source.split("\n")
  const begin = lines.findIndex((line) => line.includes(BEGIN_MARKER))
  const end = lines.findIndex((line) => line.includes(END_MARKER))
  if (begin === -1 || end < begin) return source
  const kept = [...lines.slice(0, begin), ...lines.slice(end + 1)]
  return kept.join("\n").replace(/\n{3,}/g, "\n\n")
}
